dependencies:
  cache_directories:
    - "node_modules"
    - "~/.npm"
    - "~/.meteor"
  override:
    - curl https://install.meteor.com | /bin/sh
    - npm install -g chimp
    - meteor npm install --save bcrypt
    - npm install
version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
