version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  server_tests:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: cd server && npm install && npm test
  client_tests:
    docker:
      - image: circleci/node:8-browsers
    environment:
      - CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: cd client && npm install && npm run unit
workflows:
  node-tests:
    jobs:
      - server_tests
      - client_tests